[package]
name = "tungstenite"
description = "Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming"]
keywords = ["websocket", "io", "web"]
authors = ["Alexey Galakhov"]
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/snapview/tungstenite-rs"
documentation = "https://docs.rs/tungstenite/0.5.4"
repository = "https://github.com/snapview/tungstenite-rs"
version = "0.5.4"

[features]
default = ["tls"]
tls = ["native-tls"]

[dependencies]
base64 = "0.9.0"
byteorder = "1.1.0"
bytes = "0.4.6"
httparse = "1.2.3"
input_buffer = "0.1.1"
log = "0.4.1"
rand = "0.4.2"
sha1 = "0.4.0"
url = "1.5.1"
utf-8 = "0.7.1"

[dependencies.native-tls]
optional = true
version = "0.1.5"

[dev-dependencies]
env_logger = "0.4.3"
