[package]
name = "tungstenite"
description = "Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming"]
keywords = ["websocket", "io", "web"]
authors = ["Alexey Galakhov"]
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/snapview/tungstenite-rs"
documentation = "https://docs.rs/tungstenite/0.5.4"
repository = "https://github.com/snapview/tungstenite-rs"
version = "0.5.4"

[features]
default = ["tls"]
tls = ["native-tls"]

[dependencies]
base64 = "0.9.2"
byteorder = "1.2.3"
bytes = "0.4.8"
httparse = "1.3.1"
# Required until input_buffer has new version published with Debug derive fix present
input_buffer = { git = "https://github.com/snapview/input_buffer" }
log = "0.4.2"
rand = "0.5.2"
sha1 = "0.4.0"
url = "1.7.0"
utf-8 = "0.7.2"

[dependencies.native-tls]
optional = true
version = "0.1.5"

[dev-dependencies]
env_logger = "0.5.3"

[patch.crates-io]
native-tls = { git = "https://github.com/sfackler/rust-native-tls.git" }
