[package]
name = "tungstenite"
description = "Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming"]
keywords = ["websocket", "io", "web"]
authors = ["Alexey Galakhov"]
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/snapview/tungstenite-rs"
documentation = "https://docs.rs/tungstenite/0.4.0"
repository = "https://github.com/snapview/tungstenite-rs"
version = "0.4.0"

[features]
default = ["tls"]
tls = ["native-tls"]

[dependencies]
base64 = "0.6.0"
byteorder = "1.1.0"
bytes = "0.4.4"
httparse = "1.2.3"
log = "0.3.8"
rand = "0.3.16"
sha1 = "0.2.0"
url = "1.5.1"
utf-8 = "0.7.1"

[dependencies.native-tls]
optional = true
version = "0.1.4"

[dev-dependencies]
env_logger = "0.4.3"
