[package]
name = "tungstenite"
description = "Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming"]
keywords = ["websocket", "io", "web"]
authors = ["Alexey Galakhov"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/snapview/tungstenite-rs"
documentation = "https://docs.rs/tungstenite"
repository = "https://github.com/snapview/tungstenite-rs"
version = "0.2.0"

[features]
default = ["tls"]
tls = ["native-tls"]

[dependencies]
base64 = "*"
byteorder = "*"
bytes = "*"
httparse = "*"
env_logger = "*"
log = "*"
rand = "*"
sha1 = "*"
url = "*"
utf-8 = "*"

[dependencies.native-tls]
optional = true
version = "*"
