[package]
name = "tungstenite"
description = "Lightweight stream-based WebSocket implementation"
categories = ["Web programming", "Network programming"]
keywords = ["websocket", "io", "web"]
authors = ["Alexey Galakhov"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/snapview/tungstenite-rs"
version = "0.1.0"

[features]
default = ["tls"]
tls = ["native-tls"]

[dependencies]
base64 = "0.4.0"
byteorder = "1.0.0"
bytes = "0.4.1"
httparse = "1.2.1"
env_logger = "0.4.2"
log = "0.3.7"
rand = "0.3.15"
sha1 = "0.2.0"
url = "1.4.0"
utf-8 = "0.6"

[dependencies.native-tls]
optional = true
version = "0.1.1"
