[package]
name = "tungstenite"
description = "Lightweight stream-based WebSocket implementation"
categories = ["Web programming", "Network programming"]
keywords = ["websocket", "io", "web"]
authors = ["Alexey Galakhov"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/snapview/tungstenite-rs"
version = "0.1.1"

[features]
default = ["tls"]
tls = ["native-tls"]

[dependencies]
base64 = "*"
byteorder = "*"
bytes = "*"
httparse = "*"
env_logger = "*"
log = "*"
rand = "*"
sha1 = "*"
url = "*"
utf-8 = "0.6"

[dependencies.native-tls]
optional = true
version = "*"
